/* AUTO-GENERATED by tools/gen_globals.py — do not edit */
#pragma once

BOOL W2k_resume_cdrom();
BOOL W9x_resume_cdda();
BOOL __cdecl Big_Motor(unsigned int a1, int a2);
BOOL __cdecl Small_Motor(unsigned int a1, int a2);
BOOL __cdecl controller_set_joypad(HWND hDlg, unsigned __int16 a2);
BOOL __cdecl gpu_draw_text_on_screen(LPCSTR lpchText, void *a2);
BOOL __cdecl open_file_dialog(const CHAR *a1, const CHAR *a2, CHAR *a3, const CHAR *a4, const CHAR *a5);
BOOL __cdecl zip_find_end_of_central_dir_signature(int a1, int a2, _DWORD *a3);
BOOL create_main_window();
BOOL gpu_close_output_window();
BOOL gpu_register_output_win_class();
BOOL register_win_class();
DWORD GetASPI32SupportInfo(void);
FILE *__cdecl loader_load_cheat_file(char *FileName);
FILE *cdrom_fake_write();
FILE *loader_load_cheats();
GTE_REG __cdecl gte_write_data_register(unsigned __int8 a1, GTE_REG a2);
GTE_REG gte_dpct();
GTE_REG gte_op_shifted();
HANDLE W2k_cdrom_deinit();
HANDLE __cdecl W2k_open_cdrom_device(unsigned __int8 a1);
HANDLE setup_wizard_init();
HMODULE W9x_cdrom_deinit();
HMODULE W9x_free_winaspi_dll();
HMODULE gpu_destroy();
HMODULE net_close();
HMODULE net_pause();
HMODULE net_resume();
HRESULT WINAPI DirectInputCreateA(HINSTANCE hinst, DWORD dwVersion,
                                  LPDIRECTINPUTA *ppDI, LPUNKNOWN punkOuter);
HWND gpu_create_output_window();
HWND gpu_load_plugin();
INT_PTR __stdcall bios_dialog_callback(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall controller_setup_callback(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall memcard_settings(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall search_cdrom_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall search_net_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall search_spu_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall search_video_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall setup_wizard_begin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall setup_wizard_controllers(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall setup_wizard_end(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall setup_wizard_search_bios(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall setup_wizard_search_cdrom_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall setup_wizard_search_spu_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall setup_wizard_search_video_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall spucore_configure_dialog_callback(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall w2k_cdrom_settings(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall w9x_cdrom_settings(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
LRESULT __stdcall cheat_dialog_callback(HWND hDlg, int a2, __int16 a3, int a4);
LRESULT __stdcall main_window_callback(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
_BYTE *__cdecl cont_build_controller_response_digital(char a1, _BYTE *a2);
_BYTE *__cdecl cont_build_guncon_response(char a1, _BYTE *a2);
_BYTE *__cdecl cont_build_mouse_response(char a1, _BYTE *a2);
_BYTE *__cdecl gpu_draw_free_slot(char *a1, int a2);
_BYTE *__cdecl gpu_draw_no_save_pic(char *a1, int a2);
_DWORD *W9x_cdrom_gettrackinfo();
_DWORD *__cdecl W9x_bcd_to_dword(_DWORD *a1, unsigned __int8 *a2);
_DWORD *__cdecl diInitEffectStruct(_DWORD *a1);
_DWORD *__cdecl xa_clear_adpcm_state(_DWORD *a1);
_DWORD *state_load();
_DWORD *state_save();
_WORD *__cdecl mdec_yuv_to_rgb(char *a1, _WORD *a2, _WORD *a3);
__int16 __cdecl cont_map_axis_state(unsigned __int16 a1, __int16 a2);
__int16 __cdecl cont_map_button_state(unsigned __int16 a1, __int16 a2);
__int16 __cdecl hw_reg_read_half(unsigned int a1);
__int16 __cdecl mdec_write_command(unsigned int a1);
__int16 __cdecl mem_read_half(unsigned int a1);
__int16 __cdecl sio_read_halfword(int a1);
__int16 __cdecl spu_read_register(unsigned int a1);
__int16 __cdecl spucore_read_register(__int16 a1);
__int16 __cdecl spucore_read_voice_reg(int a1, int a2);
__int16 __cdecl spucore_write_cnt(__int16 a1);
__int16 __cdecl spucore_write_dma_ctrl(__int16 a1);
__int16 __cdecl spucore_write_register(__int16 a1, __int16 a2);
__int16 __cdecl zip_read_uint16_le(int a1);
__int16 cdr_init_report_mode();
__int16 spucore_dma_read_fifo();
__int16 spucore_read_cnt();
__int16 spucore_read_dma_ctrl();
__int16 spucore_read_status_hi();
__int64 dynarec_execute();
bool __cdecl W2k_get_subchannel_status(_DWORD *a1);
bool __cdecl W2k_read_raw_sector(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        DWORD a5);
bool __cdecl W2k_read_sector_mode1(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        DWORD a5);
bool __cdecl W2k_read_sector_mode2(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        DWORD a5);
bool __cdecl W2k_read_sector_mode3(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        DWORD a5);
bool __cdecl W2k_read_sector_with_subchannel_output(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        DWORD a5,
        _DWORD *a6);
bool __cdecl W2k_send_scsi_command(const void *a1, unsigned int a2, DWORD a3, DWORD a4);
bool __cdecl W2k_send_subchannel_command(int a1);
bool __cdecl sio_controller_init(__int16 a1);
char *__cdecl dynarec_recompile_block(int a1);
char *__cdecl mdec_rl_decode(char *a1, int a2);
char *__cdecl sio_for_netplay(unsigned __int8 a1);
char *__cdecl zip_get_filename_from_path(const char *a1);
char *cdfs_read_root_directory();
char *dynarec_hw_update();
char *dynarec_invalidate();
char *mdec_init_pointers();
char W2k_cdrom_gettrackinfo();
char W2k_cdrom_init();
char W2k_cdrom_stop();
char W2k_cdrom_subchannel_read();
char W2k_find_cdrom_drive_letter();
char W9x_cdrom_init();
char W9x_cdrom_stop();
char W9x_cdrom_subchannel_read();
char W9x_init_aspi();
char __cdecl W2k_cdrom_play_cdda(unsigned int a1, int a2, unsigned __int8 a3);
char __cdecl W2k_find_track_by_min_sec(unsigned int a1, char a2);
char __cdecl W2k_get_first_last_track(_BYTE *a1, _BYTE *a2);
char __cdecl W2k_lba_to_msf(
        unsigned int a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        _BYTE *a4,
        unsigned __int8 *a5,
        unsigned __int8 *a6);
char __cdecl W2k_msf_to_lba(
        unsigned int a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        _BYTE *a4,
        _BYTE *a5,
        _BYTE *a6,
        _BYTE *a7);
char __cdecl W9x_exec_scsi_cmd(const void *a1, unsigned int a2, BYTE *a3, DWORD a4);
char __cdecl W9x_find_track_by_msf(unsigned int a1, char a2);
char __cdecl W9x_get_first_last_track(_BYTE *a1, _BYTE *a2);
char __cdecl W9x_msf_to_lba(
        unsigned int a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        _BYTE *a4,
        _BYTE *a5,
        _BYTE *a6,
        _BYTE *a7);
char __cdecl W9x_play_cdda(unsigned int a1, int a2, unsigned __int8 track_by_msf);
char __cdecl W9x_read_cd_data_only(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        BYTE *a5);
char __cdecl W9x_read_cd_sectors(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        BYTE *a5);
char __cdecl W9x_read_cd_subchannel(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        BYTE *a5);
char __cdecl W9x_read_cd_subchannel2(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        BYTE *a5);
char __cdecl W9x_read_cd_with_subchannel(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 a4,
        BYTE *a5,
        _DWORD *a6);
char __cdecl W9x_read_subchannel_status(BYTE *a1);
char __cdecl W9x_seek_cd(int a1);
char __cdecl W9x_verify_subchannel_data(unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, int a4);
char __cdecl cdr_reg0_write(char a1);
char __cdecl cdr_reg2_write(char a1);
char __cdecl cdr_set_nocd(char a1);
char __cdecl cfg_get_value(LPCSTR lpSubKey, LPCSTR lpValueName, LPBYTE lpData);
char __cdecl check_state_exists(unsigned __int8 a1);
char __cdecl cont_build_controller_response_analog(char a1, _BYTE *a2);
char __cdecl ext_CDR_bcd_to_binary(char a1, char a2);
char __cdecl ext_CDR_get_first_last_track(_BYTE *a1, _BYTE *a2);
char __cdecl ext_CDR_lba_to_msf_with_track(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        _BYTE *a4,
        _BYTE *a5,
        _BYTE *a6,
        _BYTE *a7);
char __cdecl ext_CDR_track_to_msf(__int16 a1, _BYTE *a2, _BYTE *a3, _BYTE *a4);
char __cdecl ext_CDR_verify_subchannel_data(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, int a4);
char __cdecl ext_CDRplay(int a1, char a2);
char __cdecl gpu_pack_pixels(_BYTE *a1, char a2);
char __cdecl gte_convert_to_5bit(int a1);
char __cdecl irq_rcnt_write_reg(unsigned __int16 a1, int a2);
char __cdecl iso_load(char *FileName);
char __cdecl iso_read_data(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, int a4);
char __cdecl iso_verify_sub(unsigned __int8 a1, unsigned __int8 a2, char a3, int a4);
char __cdecl loader_apply_mini_cheats(const char *a1);
char __cdecl loader_mini_cheat_find(int a1, int a2);
char __cdecl loader_mini_cheat_find_by_id(int a1, int a2);
char __cdecl loader_parse_cheat_entry(const char *a1, char *Buffer);
char __cdecl rcnt_write_reg(unsigned __int16 a1, int a2);
char __cdecl set_gpu_freeze_counter(char a1);
char __cdecl sio_schedule_transfer(char a1, char *a2);
char __cdecl spu_play_adpcm(int a1);
char __cdecl spu_write_register(unsigned int a1, __int16 a2);
char __cdecl spucore_play_adpcm(int a1);
char cdr_increment_msf();
char cdr_process_delays();
char cdr_read_data_sector();
char cdr_reset_controller();
char cdr_update_motor_status();
char check_and_clear_console_log_flush_pending(void);
char ext_CDRstop();
char ext_cdrom_load_plugin();
char get_gpu_freeze_counter();
char gpu_dma();
char gpu_dma2_interrupt();
char gpu_dma6_interrupt();
char gpu_freeze_with_counter();
char gpu_init_performance_counter();
char gte_cc();
char gte_cdp();
char gte_dcpl();
char gte_dpcs();
char gte_exec_opcode();
char gte_nccs();
char gte_ncct();
char gte_ncds();
char gte_ncdt();
char gte_ncs();
char gte_nct();
char irq_clear_hw_regs();
char mdec_timer_handler();
char net_netplay_handler();
char op_MFLO();
char ppf_load_patch();
char reopen_console_log(void);
char select_cdrom_core();
char sio_memcard1_save();
char sio_memcard2_save();
char sio_memcard_auto_save();
char sio_memcard_both_save();
char sio_memcard_load();
char sio_reset_controller_state();
char spu_close();
char spu_destroy();
char spu_load_plugin();
char spu_open();
int (*__cdecl spu_async_update(int a1))(void);
int (*ext_cdrom_deinit())(void);
int (*gpu_make_snapshot())(void);
int (*spu_update())(void);
int (__cdecl *W9x_load_winaspi_dll())(LPSRB);
int (__stdcall *__cdecl cont_update_led_and_mode(unsigned __int8 a1))(_DWORD);
int (__stdcall *__cdecl gpu_cursor(int a1, int a2, int a3))(_DWORD, _DWORD, _DWORD);
int (__stdcall *__cdecl gpu_display_flags(int a1))(_DWORD);
int (__stdcall *__cdecl gpu_do_freeze(int a1))(_DWORD, _DWORD);
int (__stdcall *gpu_hide_screen_pic())(_DWORD);
int (__stdcall *gpu_open_with_input())(_DWORD, _DWORD);
int (__stdcall *sio_reset_all())(_DWORD);
int *__cdecl cdfs_find_file(const char *a1, int *a2, int **a3);
int *__cdecl xa_decode_adpcm_block(int *a1, unsigned __int8 a2, __int16 *a3, _WORD *a4, unsigned int a5);
int JOY_Close();
int JOY_init();
int W2k_send_read_subchannel_command();
int W2k_send_read_toc_command();
int W9x_disable_subchannel_mode();
int W9x_enable_subchannel_mode();
int W9x_load_win_aspi_silent();
int __cdecl W2k_cdrom_read_data(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, char *Buffer);
int __cdecl W2k_get_scsi_address(unsigned __int8 a1, _DWORD *a2, _DWORD *a3, _DWORD *a4);
int __cdecl W2k_scsi_pass_through_direct(DWORD BytesReturned);
int __cdecl W9x_add_cdrom_device_info(BYTE a1, BYTE a2, BYTE a3);
int __cdecl W9x_cdrom_read_data(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, char *Buffer);
int __cdecl calc_bios_checksum(uint8_t *ptr, int size);
int __cdecl cdfs_read_le32(unsigned __int8 *a1);
int __cdecl cdr_bcd_to_hex(unsigned __int8 a1);
int __cdecl cdr_freeze(const char *a1, int a2);
int __cdecl cdr_get_status(int a1);
int __cdecl cdr_hex_to_bcd(unsigned __int8 a1);
int __cdecl cdr_msf_to_lba(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3);
int __cdecl cdr_unfreeze(int a1, _DWORD *a2);
int __cdecl cdr_unfreeze_new(int a1, _DWORD *a2);
int __cdecl cdrom_fake_create_file(char *FileName);
int __cdecl cdrom_fake_load_file(char *FileName);
int __cdecl cfg_set_value(LPCSTR lpSubKey, LPCSTR lpValueName, BYTE *lpData);
int __cdecl cont_reset_pad_state(unsigned __int8 a1);
int __cdecl cont_set_default(unsigned __int8 a1);
int __cdecl controller_set_keyboard(HWND hDlg, unsigned __int16 a2);
int __cdecl diGetJoystickButtonState1(int a1);
int __cdecl diGetJoystickButtonState2(int a1);
int __cdecl diGetJoystickButtonState3(int a1);
int __cdecl diGetJoystickButtonState4(int a1);
int __cdecl diSetConstantForceMagnitude(int a1, int a2);
int __cdecl diSetEffectMagnitude(int a1, int a2, int a3, int a4);
int __cdecl diSetPeriodicForceMagnitude(_DWORD *a1, int a2);
int __cdecl dynarec_compile(unsigned int ArgList, int a2);
int __cdecl ext_CDR_read(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, char *Buffer);
int __cdecl gpu_writeData(int a1);
int __cdecl gpu_writeStatus(int a1);
int __cdecl gte_clamp(int a1, int a2);
int __cdecl gte_count_leading_bits(int a1);
int __cdecl gte_freeze(const char *a1, int a2);
int __cdecl gte_read_data_register(unsigned __int8 a1);
int __cdecl gte_unfreeze(int a1, _DWORD *a2);
int __cdecl hw_reg_freeze(const char *a1, int a2);
int __cdecl hw_reg_read_word(unsigned int a1);
int __cdecl hw_reg_unfreeze(int a1, _DWORD *a2);
int __cdecl irq_dma_assert_int(unsigned __int8 a1);
int __cdecl irq_freeze(const char *a1, int a2);
int __cdecl irq_unfreeze(int a1, _DWORD *a2);
int __cdecl loader_load_demo(char *FileName);
int __cdecl loader_pll_parse_section(int a1, unsigned int *a2, unsigned int a3, const char *a4, int a5);
int __cdecl loader_set_bios_name(const char *a1);
int __cdecl loader_set_filename(const char *a1);
int __cdecl mdec_freeze(const char *a1, int a2);
int __cdecl mdec_freeze2(const char *a1, int a2);
int __cdecl mdec_handle_special_command(int a1);
int __cdecl mdec_idct_sse(__m64 *a1, int a2);
int __cdecl mdec_set_scale_table(int a1);
int __cdecl mdec_unfreeze(int a1, _DWORD *a2);
int __cdecl mdec_unfreeze2(int a1, _DWORD *a2);
int __cdecl mem_dma_read(unsigned int a1);
int __cdecl mem_freeze(const char *a1, int a2);
int __cdecl mem_read_word(unsigned int a1);
int __cdecl mem_unfreeze(int a1, _DWORD *a2);
int __cdecl parse_command_line_options(int a1, int a2);
int __cdecl ppf_parse_and_build(int a1, int a2, unsigned int a3);
int __cdecl setup_wizard_callback(HWND hWndParent);
int __cdecl sio_freeze(const char *a1, int a2);
int __cdecl sio_handle_config_command(char a1, int a2, char a3);
int __cdecl sio_read_register(int a1, char a2);
int __cdecl sio_read_word(int a1);
int __cdecl spucore_dma_write_fifo(__int16 a1);
int __cdecl spucore_freeze(const char *a1, int a2);
int __cdecl spucore_set_dma_address(unsigned __int16 a1);
int __cdecl spucore_set_pitchmod(unsigned int a1);
int __cdecl spucore_set_voiceon(unsigned int a1);
int __cdecl spucore_unfreeze(int a1, _DWORD *a2);
int __cdecl spucore_voice_key_off(int a1);
int __cdecl spucore_voice_key_on(int a1);
int __cdecl spucore_write_status_hi(__int16 a1);
int __cdecl spucore_write_voice_reg(int a1, int a2, unsigned __int16 a3);
int __cdecl sub_42B080(const char *a1, int a2);
int __cdecl xa_decode_stereo_blocks(int a1, int a2);
int __cdecl xa_decode_wrapper(_DWORD *a1, int a2, int a3);
int __cdecl xa_get_audio_mode(int a1);
int __cdecl xa_setup_adpcm_decoder(_DWORD *a1, int a2, int a3, int a4);
int __cdecl zip_build_huffman_tree(
        _DWORD *a1,
        unsigned int a2,
        unsigned int a3,
        int a4,
        int a5,
        _DWORD *a6,
        unsigned int *a7);
int __cdecl zip_compare_filename_case_insensitive(const char *a1, const char *a2);
int __cdecl zip_extract_file(char *FileName, char *arg4, LPVOID *arg8, size_t *a4);
int __cdecl zip_free_huffman_tree(int a1);
int __cdecl zip_get_file_size(FILE *Stream, _DWORD *a2);
int __cdecl zip_inflate_block(int *a1);
int __cdecl zip_inflate_data_with_trees(int a1, int a2, unsigned int a3, unsigned int a4);
int __cdecl zip_load_central_directory(FILE *Stream, const char *arg4, int a3, ZipCentralDirectoryEntry *a2);
int __cdecl zip_load_file(char *FileName);
int __cdecl zip_load_local_file_headers(FILE *Stream, int arg4, ZipCentralDirectoryEntryInMem *a2);
int __cdecl zip_locate_central_dir(FILE *Stream, int *a2);
int __cdecl zip_parse_cd_entry(ZipCentralDirectoryEntry *a1, ZipCentralDirectoryEntryInMem *a2);
int __cdecl zip_read_compressed_data_to_buffer(FILE *Stream, int a2, int a3, LPVOID *a4);
int __cdecl zip_read_local_file_header(FILE *Stream, int a2, ZipLocalFileHeaderInMem *a3, unsigned __int8 *Buffer);
int __stdcall WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd);
int __stdcall about_callback(HWND hDlg, int a2, __int16 a3, int a4);
int __stdcall diEnumEffectsCallback(_DWORD *a1, _DWORD *a2);
int __stdcall gpu_output_win_callback(HWND hWnd, UINT a2, WPARAM a3, LPARAM a4);
int alloc_console(void);
int cdr_get_response_status();
int cfg_cdrom_iso_set_path();
int cfg_cdrom_set_hain_target_lun();
int cfg_cdrom_set_letter();
int cfg_load_settings();
int cfg_save_settings();
int clear_memory();
int cont_process_input();
int cpu_clear_regs();
int cpu_execute();
int dbg_print(const char *Format, ...);
int diAcquireAllDevices();
int diAcquireMouseDevice();
int diEnumDevicesCallback(int a1, _DWORD *a2, int a3);
int diGetClampedMouseX();
int diGetClampedMouseY();
int diGetMouseState();
int diInitDirectInput();
int diShutdownDirectInput();
int diUnacquireAllDevices();
int diUpdateDeviceStates();
int diUpdateJoystickStates();
int free_console(void);
int gpu_close();
int gpu_frame_update();
int gpu_open();
int gpu_readData();
int gpu_readStatus();
int gte_clear_regs();
int gte_op();
int gte_rtps();
int gte_rtpt();
int irq_sio_update();
int iso_close();
int joy_init(void);
int joy_issue_big_motor();
int joy_issue_small_motor();
int loader_cdrom_detect_region();
int loader_check_bios_file_exists();
int loader_touch_demo_file();
int mdec_decode();
int mdec_init();
int mdec_init_color_tables();
int mem_clear_memory();
int net_fill_input();
int net_load_plugin();
int net_open();
int save_temp_memcard1();
int save_temp_memcard2();
int select_plugins_backend();
int spucore_destroy();
int spucore_init();
int spucore_init_dsound();
int spucore_init_gauss_table();
int spucore_update_dsound();
int spucore_update_thunk();
int xa_decode_mono_blocks(int a1, int a2, int a3);
int zip_inflate_file();
int zip_print(char *Format, ...);
size_t __cdecl cdrom_fake_read_portion(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, void *Buffer);
size_t __cdecl loader_pll_get_file_size(const char *a1);
uint32_t __cdecl zip_read_uint32_le(unsigned __int8 *a1);
uint8_t *dynarec_init();
unsigned __int8 __cdecl W2k_check_subchannel_data(unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, int a4);
unsigned __int8 __cdecl W9x_get_track_start_lba(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 *a4,
        unsigned __int8 *a5,
        unsigned __int8 *a6);
unsigned __int8 __cdecl cdfs_load_executable(char *Buffer);
unsigned __int8 __cdecl cdfs_parse_system_cnf_for_exec(int a1, int a2, char *Buffer, int *a4, int **a5);
unsigned __int8 __cdecl ext_CDR_lba_to_msf(
        unsigned __int8 a1,
        unsigned __int8 a2,
        unsigned __int8 a3,
        unsigned __int8 *a4,
        unsigned __int8 *a5,
        unsigned __int8 *a6);
unsigned __int8 __cdecl spucore_decode_adpcm_block(int a1);
unsigned int __cdecl W2k_track_to_msf(int a1, _BYTE *a2, _BYTE *a3, _BYTE *a4);
unsigned int __cdecl W9x_track_to_msf(__int16 a1, _BYTE *a2, _BYTE *a3, _BYTE *a4);
unsigned int __cdecl cdfs_read_data(int a1, int a2, unsigned int a3, void *a4);
unsigned int __cdecl diCreateEffectHelper(int a1, _DWORD *a2);
unsigned int __cdecl diSetupConstantForceEffect(int a1, int a2);
unsigned int __cdecl diSetupPeriodicForceEffect(_DWORD *a1, int a2);
unsigned int __cdecl dynarec_invalidate_range(int a1, int a2);
unsigned int __cdecl mem_gpu_dma_read(unsigned int a1);
unsigned int __cdecl sio_build_multitap_response(_BYTE *a1, _DWORD *a2);
unsigned int __cdecl zip_copy_sliding_window_to_output(const void *a1, unsigned int a2);
unsigned int cdr_dma();
unsigned int cpu_load_bios_shell();
unsigned int irq_cpu_interrupt();
unsigned int spucore_generate_samples();
unsigned long get_tick_count(void);
void *__cdecl cdrom_fake_write_portion(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, void *Buffer);
void W2k_reset_cdda_state();
void W9x_reset_cdrom_state();
void __cdecl cdr_reg1_write(unsigned __int8 a1);
void __cdecl cdr_reg3_write(char a1);
void __cdecl gpu_freeze(const char *a1, int ArgList, const char *a3);
void __cdecl gpu_show_screen_pic(unsigned __int8 a1);
void __cdecl gpu_unfreeze(int a1, _DWORD *ArgList);
void __cdecl hw_reg_write_word(unsigned int a1, unsigned int a2);
void __cdecl loader_check_demo_header(FILE *Stream, int a2);
void __cdecl loader_load_file(char *a1, size_t Size);
void __cdecl mdec_idct_blocks(int a1);
void __cdecl mdec_y_to_mono(unsigned int *a1, __m64 *a2, int a3);
void __cdecl mem_gpu_dma_write(unsigned int a1, unsigned int a2);
void __cdecl mem_hw_reg_read_byte(unsigned int a1);
void __cdecl mem_hw_reg_write_byte(unsigned int a1, char a2);
void __cdecl mem_hw_reg_write_half(unsigned int a1, unsigned __int16 a2);
void __cdecl mem_write_half(unsigned int a1, unsigned __int16 a2);
void __cdecl mem_write_word(unsigned int a1, unsigned int a2);
void __cdecl ppf_apply_patch_to_sector(int a1, int a2);
void __cdecl sio_command(char *a1);
void __cdecl sio_unfreeze(int a1, _DWORD *a2);
void __cdecl sio_write_data_byte(int a1, char a2);
void __cdecl spu_freeze(const char *a1, int a2);
void __cdecl spu_unfreeze(int a1, _DWORD *a2);
void cdr_play_tick();
void cdr_queue_response();
void cdr_spinup_motor();
void cdrom_assert_int();
void dbg_print_no_flush(const char *Format, ...);
void dump_log(FILE *Stream, const char *Format, ...);
void dynarec_deinit();
void epsxe_main_loop_runner();
void ext_CDR_reset_state();
void fatal_error_with_message_box(const char *Format, ...);
void gpu_clear_dynarec_callback();
void irq_cdrom_assert_int();
void irq_sio_assert_int();
void irq_spu_registered_callback();
void loader_load_bios();
void loader_load_zip();
void mdec_dma_in_handler();
void mdec_sse_m_empty();
void mem_init_memory_handlers();
void memset32(void *dst, unsigned int value, unsigned int count);
void nullsub_1();
void op_ADD();
void op_ADDI();
void op_AND();
void op_ANDI();
void op_BCONDZ();
void op_BEQ();
void op_BGEZ();
void op_BGEZAL();
void op_BGTZ();
void op_BLEZ();
void op_BLTZ();
void op_BLTZAL();
void op_BNE();
void op_BREAK();
void op_COP0();
void op_DIV();
void op_DIVU();
void op_J();
void op_JAL();
void op_JALR();
void op_JR();
void op_LB();
void op_LBU();
void op_LH();
void op_LHU();
void op_LUI();
void op_LW();
void op_LWC2();
void op_LWL();
void op_LWR();
void op_MFC0();
void op_MFHI();
void op_MTC0();
void op_MTHI();
void op_MTLO();
void op_MULT();
void op_MULTU();
void op_NOR();
void op_OR();
void op_ORI();
void op_RFE();
void op_SB();
void op_SH();
void op_SLL();
void op_SLLV();
void op_SLT();
void op_SLTI();
void op_SLTIU();
void op_SLTU();
void op_SPECIAL();
void op_SRA();
void op_SRAV();
void op_SRL();
void op_SRLV();
void op_SUB();
void op_SW();
void op_SWC2();
void op_SWL();
void op_SWR();
void op_SYSCALL();
void op_UNKNOWN();
void op_XOR();
void op_XORI();
void ppf_free();
void print_develop_options();
void print_usage();
void print_version();
void save_load_state();
void set_console_log_flush_pending(void);
void sio_assert_int();
void sio_read_data_byte();
void sio_trigger_rx_ready_irq();
void spu_dma();
void spu_set_adpcm_flag();
void spucore_dma();
void ui_error(const char *Format, ...);
