#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern DWORD (__stdcall *GetASPI32SupportInfo_cb)(void);
extern int (__cdecl *SendASPI32Command_cb)(LPSRB);
extern unsigned char SubchannelW9xCaching;
extern unsigned char w9x_toc_buffer;
extern unsigned char w9x_toc_first_track;
extern unsigned char w9x_toc_last_track;
extern unsigned char w9x_toc_track_control[1];
extern unsigned char w9x_toc_track_entries[0x33a];
extern unsigned char cd_device_reserved0[1];
extern unsigned char cd_device_product[0x10];
extern unsigned char cd_device_reserved1[1];
extern unsigned char cd_device_reserved2[1];
extern unsigned char cd_device_extra[0x14];
extern unsigned char cd_device_reserved3[1];
extern unsigned int cdrom_haid;
extern unsigned int cdrom_lun;
extern unsigned int cdrom_target;
extern unsigned int w9x_play_cdb;
extern unsigned int w9x_play_cdb2;
extern unsigned int w9x_stop_cdb;
extern unsigned int w9x_stop_cdb2;
extern unsigned int w9x_resume_cdb;
extern unsigned int w9x_resume_cdb2;
extern unsigned int w9x_cdrom_info;
extern unsigned int w9x_cdda_playing;
extern unsigned int w9x_cdda_resume_pending;
extern unsigned int cached_sector_lba;
extern unsigned int cd_device_vendor;
extern unsigned int cd_device_vendor2;
extern unsigned int cd_device_revision;
extern unsigned int cd_device_haid;
extern unsigned int cd_device_target;
extern unsigned int cd_device_lun[0xf1];
extern unsigned short w9x_play_cdb3;
extern unsigned short w9x_stop_cdb3;
extern unsigned short w9x_resume_cdb3;

/* Function prototypes (previously generated in src/_gen) */
int __cdecl W9x_add_cdrom_device_info(BYTE a1, BYTE a2, BYTE a3);
_DWORD *__cdecl W9x_bcd_to_dword(_DWORD *a1, unsigned __int8 *a2);
HMODULE W9x_cdrom_deinit();
_DWORD *W9x_cdrom_gettrackinfo();
char W9x_cdrom_init();
int __cdecl W9x_cdrom_read_data(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, char *Buffer);
char W9x_cdrom_stop();
char W9x_cdrom_subchannel_read();
int W9x_disable_subchannel_mode();
int W9x_enable_subchannel_mode();
char __cdecl W9x_exec_scsi_cmd(const void *a1, unsigned int a2, BYTE *a3, DWORD a4);
char __cdecl W9x_find_track_by_msf(unsigned int a1, char a2);
HMODULE W9x_free_winaspi_dll();
char __cdecl W9x_get_first_last_track(_BYTE *a1, _BYTE *a2);
unsigned __int8 __cdecl W9x_get_track_start_lba( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 *a4, unsigned __int8 *a5, unsigned __int8 *a6);
char W9x_init_aspi();
int W9x_load_win_aspi_silent();
int (__cdecl *W9x_load_winaspi_dll())(LPSRB);
char __cdecl W9x_msf_to_lba( unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, _BYTE *a4, _BYTE *a5, _BYTE *a6, _BYTE *a7);
char __cdecl W9x_play_cdda(unsigned int a1, int a2, unsigned __int8 track_by_msf);
char __cdecl W9x_read_cd_data_only( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_sectors( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_subchannel( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_subchannel2( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_with_subchannel( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5, _DWORD *a6);
char __cdecl W9x_read_subchannel_status(BYTE *a1);
void W9x_reset_cdrom_state();
BOOL W9x_resume_cdda();
char __cdecl W9x_seek_cd(int a1);
unsigned int __cdecl W9x_track_to_msf(__int16 a1, _BYTE *a2, _BYTE *a3, _BYTE *a4);
char __cdecl W9x_verify_subchannel_data(unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, int a4);
