#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern unsigned char SubchannelW2kCaching;
extern unsigned char byte_455945;
extern unsigned char byte_457338;
extern unsigned char byte_4FD9C8;
extern unsigned char byte_4FD9D0;
extern unsigned char byte_4FD9D4;
extern unsigned char byte_4FD9E3;
extern unsigned char byte_4FFC40;
extern unsigned char byte_4FFC42;
extern unsigned char byte_4FFC43;
extern unsigned char byte_4FFC45[1];
extern unsigned char byte_4FFC46[0x31e];
extern unsigned char byte_4FFF84[1];
extern unsigned char byte_4FFF90[0x924];
extern unsigned char byte_5008B4[1];
extern unsigned char byte_5008B7;
extern unsigned char cdrom_letter;
extern unsigned int dword_45733C;
extern unsigned int dword_457340;
extern unsigned int dword_457348;
extern unsigned int dword_45734C;
extern unsigned int dword_457350;
extern unsigned int dword_457358;
extern unsigned int dword_45735C;
extern unsigned int dword_4FD9D8;
extern unsigned int dword_4FD9DC;
extern unsigned int dword_5008B8;
extern unsigned int dword_5008BC;
extern unsigned int dword_5008C0[0x10d1];
extern unsigned int dword_504C04[1];
extern unsigned int dword_504C08;
extern unsigned int dword_504C0C;
extern unsigned int dword_504C10[0x1d];
extern unsigned int dword_504C84;
extern unsigned int dword_504C88;
extern unsigned int dword_504C8C;
extern unsigned int dword_5053E0;
extern unsigned int dword_5053E4;
extern unsigned int dword_5053E8;
extern unsigned int dword_5053EC;
extern unsigned int dword_50C280[0x9];
extern unsigned int hObject;
extern unsigned char sound_use_cdda;
extern unsigned short word_457344;
extern unsigned short word_457354;
extern unsigned short word_457360;

/* Function prototypes (previously generated in src/_gen) */
HANDLE W2k_cdrom_deinit();
char W2k_cdrom_gettrackinfo();
char W2k_cdrom_init();
char __cdecl W2k_cdrom_play_cdda(unsigned int a1, int a2, unsigned __int8 a3);
int __cdecl W2k_cdrom_read_data(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, char *Buffer);
char W2k_cdrom_stop();
char W2k_cdrom_subchannel_read();
unsigned __int8 __cdecl W2k_check_subchannel_data(unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, int a4);
char W2k_find_cdrom_drive_letter();
char __cdecl W2k_find_track_by_min_sec(unsigned int a1, char a2);
char __cdecl W2k_get_first_last_track(_BYTE *a1, _BYTE *a2);
int __cdecl W2k_get_scsi_address(unsigned __int8 a1, _DWORD *a2, _DWORD *a3, _DWORD *a4);
bool __cdecl W2k_get_subchannel_status(_DWORD *a1);
char __cdecl W2k_lba_to_msf( unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, _BYTE *a4, unsigned __int8 *a5, unsigned __int8 *a6);
char __cdecl W2k_msf_to_lba( unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, _BYTE *a4, _BYTE *a5, _BYTE *a6, _BYTE *a7);
HANDLE __cdecl W2k_open_cdrom_device(unsigned __int8 a1);
bool __cdecl W2k_read_raw_sector( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, DWORD a5);
bool __cdecl W2k_read_sector_mode1( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, DWORD a5);
bool __cdecl W2k_read_sector_mode2( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, DWORD a5);
bool __cdecl W2k_read_sector_mode3( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, DWORD a5);
bool __cdecl W2k_read_sector_with_subchannel_output( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, DWORD a5, _DWORD *a6);
void W2k_reset_cdda_state();
BOOL W2k_resume_cdrom();
int __cdecl W2k_scsi_pass_through_direct(DWORD BytesReturned);
int W2k_send_read_subchannel_command();
int W2k_send_read_toc_command();
bool __cdecl W2k_send_scsi_command(const void *a1, unsigned int a2, DWORD a3, DWORD a4);
bool __cdecl W2k_send_subchannel_command(int a1);
unsigned int __cdecl W2k_track_to_msf(int a1, _BYTE *a2, _BYTE *a3, _BYTE *a4);
