#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern DWORD (__stdcall *GetASPI32SupportInfo_cb)(void);
extern int (__cdecl *SendASPI32Command_cb)(LPSRB);
extern unsigned char SubchannelW9xCaching;
extern unsigned char byte_504CA0;
extern unsigned char byte_504CA2;
extern unsigned char byte_504CA3;
extern unsigned char byte_504CA5[1];
extern unsigned char byte_504CA6[0x33a];
extern unsigned char byte_504FE8[1];
extern unsigned char byte_504FE9[0x10];
extern unsigned char byte_504FF9[1];
extern unsigned char byte_504FFE[1];
extern unsigned char byte_504FFF[0x14];
extern unsigned char byte_505013[1];
extern unsigned int cdrom_haid;
extern unsigned int cdrom_lun;
extern unsigned int cdrom_target;
extern unsigned int dword_456FB4;
extern unsigned int dword_456FB8;
extern unsigned int dword_456FC0;
extern unsigned int dword_456FC4;
extern unsigned int dword_456FCC;
extern unsigned int dword_456FD0;
extern unsigned int dword_4FD9BC;
extern unsigned int dword_4FD9C0;
extern unsigned int dword_4FD9C4;
extern unsigned int dword_4FFF80;
extern unsigned int dword_504FE0;
extern unsigned int dword_504FE4;
extern unsigned int dword_504FFA;
extern unsigned int dword_505014;
extern unsigned int dword_505018;
extern unsigned int dword_50501C[0xf1];
extern unsigned short word_456FBC;
extern unsigned short word_456FC8;
extern unsigned short word_456FD4;

/* Function prototypes (previously generated in src/_gen) */
int __cdecl W9x_add_cdrom_device_info(BYTE a1, BYTE a2, BYTE a3);
_DWORD *__cdecl W9x_bcd_to_dword(_DWORD *a1, unsigned __int8 *a2);
HMODULE W9x_cdrom_deinit();
_DWORD *W9x_cdrom_gettrackinfo();
char W9x_cdrom_init();
int __cdecl W9x_cdrom_read_data(unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, char *Buffer);
char W9x_cdrom_stop();
char W9x_cdrom_subchannel_read();
int W9x_disable_subchannel_mode();
int W9x_enable_subchannel_mode();
char __cdecl W9x_exec_scsi_cmd(const void *a1, unsigned int a2, BYTE *a3, DWORD a4);
char __cdecl W9x_find_track_by_msf(unsigned int a1, char a2);
HMODULE W9x_free_winaspi_dll();
char __cdecl W9x_get_first_last_track(_BYTE *a1, _BYTE *a2);
unsigned __int8 __cdecl W9x_get_track_start_lba( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 *a4, unsigned __int8 *a5, unsigned __int8 *a6);
char W9x_init_aspi();
int W9x_load_win_aspi_silent();
int (__cdecl *W9x_load_winaspi_dll())(LPSRB);
char __cdecl W9x_msf_to_lba( unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, _BYTE *a4, _BYTE *a5, _BYTE *a6, _BYTE *a7);
char __cdecl W9x_play_cdda(unsigned int a1, int a2, unsigned __int8 track_by_msf);
char __cdecl W9x_read_cd_data_only( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_sectors( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_subchannel( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_subchannel2( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5);
char __cdecl W9x_read_cd_with_subchannel( unsigned __int8 a1, unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, BYTE *a5, _DWORD *a6);
char __cdecl W9x_read_subchannel_status(BYTE *a1);
void W9x_reset_cdrom_state();
BOOL W9x_resume_cdda();
char __cdecl W9x_seek_cd(int a1);
unsigned int __cdecl W9x_track_to_msf(__int16 a1, _BYTE *a2, _BYTE *a3, _BYTE *a4);
char __cdecl W9x_verify_subchannel_data(unsigned int a1, unsigned __int8 a2, unsigned __int8 a3, int a4);
