#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern unsigned char cdr_status_command_2[8];
extern unsigned char cdr_status_command_3[8];
extern unsigned char dynarec_clear_needed;
extern int dynarec_clear_request;
extern unsigned char g_KeyboardStatePrev[1];
extern unsigned int g_MouseButtons;
extern unsigned char gpu_keyboard_state[0x1b];
extern unsigned int guncon_position;
extern int increase_slot_state_request;
extern unsigned char joystick_button_state1[4];
extern unsigned char joystick_button_state2[4];
extern unsigned char joystick_button_state3[4];
extern unsigned char joystick_button_state4[4];
extern int keyboard_escape_pressed[2];
extern int load_state_request;
extern int make_snapshot_request[2];
extern unsigned int mdec_disable_flag[1];
extern int mouse_accumulated_x;
extern int mouse_accumulated_y;
extern unsigned int mouse_buttons_state;
extern int mouse_delta_x;
extern int mouse_delta_y;
extern int netplay_reset_request;
extern unsigned short pad1_analog_joy2_x;
extern unsigned short pad1_analog_joy2_y;
extern unsigned short pad1_analog_joy_x;
extern unsigned short pad1_analog_joy_y;
extern unsigned short pad1_buttons_high;
extern unsigned short pad1_buttons_low;
extern unsigned short pad2_analog_joy2_x;
extern unsigned short pad2_analog_joy2_y;
extern unsigned short pad2_analog_joy_x;
extern unsigned short pad2_analog_joy_y;
extern unsigned short pad2_buttons_high;
extern unsigned short pad2_buttons_low;
extern unsigned short pad3_analog_joy2_x;
extern unsigned short pad3_analog_joy2_y;
extern unsigned short pad3_analog_joy_x;
extern unsigned short pad3_analog_joy_y;
extern unsigned short pad3_buttons_high;
extern unsigned short pad3_buttons_low;
extern unsigned short pad4_analog_joy2_x;
extern unsigned short pad4_analog_joy2_y;
extern unsigned short pad4_analog_joy_x;
extern unsigned short pad4_analog_joy_y;
extern unsigned short pad4_buttons_high;
extern unsigned short pad4_buttons_low;
extern int save_state_request;
extern int screen_pic_display_counter;
extern int selected_slot_for_mode_switch;
extern int sio_irq_assert_request[2];
extern int switch_controller_slot_request;
extern int toggle_pad_mode_request;
extern int toggle_sio_irq_request;
extern int toggle_xenogears_trick_request;
extern int ui_feedback_timer;
extern unsigned char xenogears_trick_enabled;

/* Function prototypes (previously generated in src/_gen) */
char __cdecl cont_build_controller_response_analog(char a1, _BYTE *a2);
_BYTE *__cdecl cont_build_controller_response_digital(char a1, _BYTE *a2);
_BYTE *__cdecl cont_build_guncon_response(char a1, _BYTE *a2);
_BYTE *__cdecl cont_build_mouse_response(char a1, _BYTE *a2);
__int16 __cdecl cont_map_axis_state(unsigned __int16 a1, __int16 a2);
__int16 __cdecl cont_map_button_state(unsigned __int16 a1, __int16 a2);
int cont_process_input();
int __cdecl cont_reset_pad_state(unsigned __int8 a1);
int __cdecl cont_set_default(unsigned __int8 a1);
int (__stdcall *__cdecl cont_update_led_and_mode(unsigned __int8 a1))(_DWORD);
