#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern int (__stdcall *GPUabout_0)();
extern int (__stdcall *GPUinit_0)();
extern int (__stdcall *GPUshutdown_0)();
extern int (__stdcall *GPUtest_0)();
extern int (__cdecl *PSEconfigure)();
extern int (__cdecl *PSEgetLibName)();
extern int (__cdecl *PSEgetLibType)();
extern int (__cdecl *PSEgetLibVersion)();
extern char aW[8];
extern char asc_44E24C[64];
extern unsigned char extended_key_states_1[1];
extern unsigned char extended_key_states_2[1];
extern unsigned char extended_key_states_3[0xa0];
extern unsigned char plugin_name_list_shift[0x380];
extern unsigned char pad_keymap_dialog_copy[0x20];
extern unsigned char plugin_name_list[0x4];
extern unsigned char plugin_name_list_tail[0x7ffc];
extern unsigned int controller_port_modes[8];
extern unsigned int found_plugin_count;
extern unsigned int joypad_button_map[1];
extern unsigned int pad2_small_motor_type;
extern unsigned int pad4_small_motor_type[1];
extern unsigned int saved_pad_joypad_buttons;
extern unsigned int saved_pad_mdec_disable_flag;
extern unsigned char edit_button_id;
extern unsigned int g_EffectType2[1];
extern unsigned int g_PlayerDeviceMap4[1];
extern unsigned char joy_names[14];
extern unsigned char multitap_1;
extern unsigned short nIDDlgItem;
extern unsigned char pad_number_menu_selection;
extern unsigned char stru_44C148[13];
extern unsigned char temp_path[0x400];
extern unsigned short controller_button_dlg_ids[9];
extern unsigned short pad_key_assignments[4];

/* Function prototypes (previously generated in src/_gen) */
int __stdcall about_callback(HWND hDlg, int a2, __int16 a3, int a4);
INT_PTR __stdcall bios_dialog_callback(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
int __cdecl calc_bios_checksum(uint8_t *ptr, int size);
LRESULT __stdcall cheat_dialog_callback(HWND hDlg, int a2, __int16 a3, int a4);
INT_PTR __stdcall controller_setup_callback(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall memcard_settings(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
BOOL __cdecl open_file_dialog(const CHAR *a1, const CHAR *a2, CHAR *a3, const CHAR *a4, const CHAR *a5);
INT_PTR __stdcall search_cdrom_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall search_net_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall search_spu_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall search_video_plugin(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall spucore_configure_dialog_callback(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
INT_PTR __stdcall w9x_cdrom_settings(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4);
