#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern LARGE_INTEGER Frequency;
extern unsigned int GPUabout;
extern int (__stdcall *GPUclose)();
extern unsigned int GPUconfigure;
extern int (__stdcall *GPUcursor)();
extern int (__stdcall *GPUdisplayFlags)();
extern int (__stdcall *GPUdmaChain)();
extern int (__stdcall *GPUfreeze)();
extern unsigned int GPUgetMode;
extern int (__stdcall *GPUgetScreenPic)();
extern int (__stdcall *GPUinit)();
extern int (__stdcall *GPUmakeSnapshot)();
extern int (__stdcall *GPUopen)();
extern int (__stdcall *GPUreadData)();
extern int (__stdcall *GPUreadDataMem)();
extern int (__stdcall *GPUreadStatus)();
extern unsigned int GPUsetMode;
extern int (__stdcall *GPUshowScreenPic)();
extern int (__stdcall *GPUshutdown)();
extern unsigned int GPUtest;
extern int (__stdcall *GPUupdateLace)();
extern int (__stdcall *GPUwriteData)();
extern int (__stdcall *GPUwriteDataMem)();
extern int (__stdcall *GPUwriteStatus)();
extern LARGE_INTEGER PerformanceCount;
extern unsigned int dword_50ADD4;
extern MSG g_msg;
extern unsigned char gpu_closed;
extern unsigned char gpu_dma2_delay_counter;
extern unsigned char gpu_dma2_state;
extern unsigned char gpu_dma6_delay_counter;
extern unsigned int gpu_dma_address;
extern unsigned int gpu_dma_channel_status[1];
extern unsigned int gpu_dma_control;
extern unsigned int gpu_hInstance;
extern LARGE_INTEGER gpu_performance_counter;
extern unsigned __int64 gpu_performance_threshold;
extern unsigned char gpu_save_pic_data[24];
extern unsigned int hGpuModule;
extern unsigned int hInst_For_DInput;
extern unsigned int hOutputWnd;
extern unsigned char use_performance_counters;

/* Function prototypes (previously generated in src/_gen) */
void gpu_clear_dynarec_callback();
int gpu_close();
BOOL gpu_close_output_window();
HWND gpu_create_output_window();
int (__stdcall *__cdecl gpu_cursor(int a1, int a2, int a3))(_DWORD, _DWORD, _DWORD);
HMODULE gpu_destroy();
int (__stdcall *__cdecl gpu_display_flags(int a1))(_DWORD);
char gpu_dma();
char gpu_dma2_interrupt();
char gpu_dma6_interrupt();
int (__stdcall *__cdecl gpu_do_freeze(int a1))(_DWORD, _DWORD);
_BYTE *__cdecl gpu_draw_free_slot(char *a1, int a2);
_BYTE *__cdecl gpu_draw_no_save_pic(char *a1, int a2);
BOOL __cdecl gpu_draw_text_on_screen(LPCSTR lpchText, void *a2);
int gpu_frame_update();
void __cdecl gpu_freeze(const char *a1, int ArgList, const char *a3);
int (__stdcall *gpu_hide_screen_pic())(_DWORD);
char gpu_init_performance_counter();
HWND gpu_load_plugin();
int (*gpu_make_snapshot())(void);
int gpu_open();
int (__stdcall *gpu_open_with_input())(_DWORD, _DWORD);
int __stdcall gpu_output_win_callback(HWND hWnd, UINT a2, WPARAM a3, LPARAM a4);
char __cdecl gpu_pack_pixels(_BYTE *a1, char a2);
int gpu_readData();
int gpu_readStatus();
BOOL gpu_register_output_win_class();
void __cdecl gpu_show_screen_pic(unsigned __int8 a1);
void __cdecl gpu_unfreeze(int a1, _DWORD *ArgList);
int __cdecl gpu_writeData(int a1);
int __cdecl gpu_writeStatus(int a1);
