#pragma once

typedef struct _KBD_NAME {
	char text[13];
} KBD_NAME;

typedef struct _JOY_NAME {
	char text[14];
} JOY_NAME;
/* Decompiled globals (previously generated in src/_gen) */
extern GUID GUID_Keyboard;
extern GUID GUID_Mouse;
extern unsigned char g_directinput_initialized;
extern unsigned char joystick_button_1_state[1];
extern unsigned char joystick_button_2_state[1];
extern unsigned char joystick_button_3_state[1];
extern unsigned char joystick_button_4_state[1];
extern unsigned char joystick_button_5_state[1];
extern unsigned char joystick_button_6_state[1];
extern unsigned char joystick_button_7_state[1];
extern unsigned char joystick_button_8_state[1];
extern unsigned char joystick_button_9_state[1];
extern unsigned char joystick_button_10_state[1];
extern unsigned char joystick_button_11_state[1];
extern unsigned char joystick_button_12_state[1];
extern unsigned char joystick_button_13_state[1];
extern unsigned char joystick_button_14_state[1];
extern unsigned char joystick_button_15_state[1];
extern unsigned char joystick_button_16_state[0x101];
extern unsigned char pad_axis_1_positive_pressed[1];
extern unsigned char pad_axis_1_negative_pressed[1];
extern unsigned char pad_axis_2_positive_pressed[1];
extern unsigned char pad_axis_2_negative_pressed[1];
extern unsigned char pad_axis_3_positive_pressed[1];
extern unsigned char pad_axis_3_negative_pressed[1];
extern unsigned char pad_axis_4_positive_pressed[1];
extern unsigned char pad_axis_4_negative_pressed[1];
extern unsigned char pad_axis_5_positive_pressed[1];
extern unsigned char pad_axis_5_negative_pressed[1];
extern unsigned char pad_axis_6_positive_pressed[1];
extern unsigned char pad_axis_6_negative_pressed[1];
extern unsigned char pad_axis_7_positive_pressed[1];
extern unsigned char pad_axis_7_negative_pressed[1];
extern unsigned char pad_button_1_pressed[1];
extern unsigned char pad_button_2_pressed[1];
extern unsigned char pad_button_3_pressed[1];
extern unsigned char pad_button_4_pressed[1];
extern unsigned char pad_button_5_pressed[1];
extern unsigned char pad_button_6_pressed[1];
extern unsigned char pad_button_7_pressed[1];
extern unsigned char pad_button_8_pressed[1];
extern unsigned char pad_button_9_pressed[1];
extern unsigned char pad_button_10_pressed[1];
extern unsigned char pad_button_11_pressed[1];
extern unsigned char pad_button_12_pressed[1];
extern unsigned char pad_button_13_pressed[1];
extern unsigned char pad_button_14_pressed[1];
extern unsigned char pad_button_15_pressed[1];
extern unsigned char pad_button_16_pressed[0x61];
extern unsigned char pad_pov_right_pressed[1];
extern unsigned char pad_pov_down_pressed[1];
extern unsigned char pad_pov_left_pressed[0x7d];
extern unsigned int joystick_axis_2_state[1];
extern unsigned int joystick_axis_3_state[1];
extern unsigned int joystick_axis_4_state[1];
extern unsigned int joystick_axis_5_state[1];
extern unsigned int joystick_axis_6_state[1];
extern unsigned int joystick_axis_7_state[1];
extern unsigned int joystick_pov_hat_value[0x4];
extern unsigned int joystick_z_axis_positive_triggered[0x10];
extern unsigned int joystick_button_3_triggered[0x10];
extern unsigned int joystick_button_4_triggered[0x10];
extern unsigned int joystick_button_5_triggered[0x10];
extern unsigned int joystick_button_6_triggered[0x10];
extern unsigned int joystick_button_7_triggered[0x10];
extern unsigned int joystick_button_8_triggered[0x10];
extern unsigned int joystick_button_9_triggered[0x10];
extern unsigned int joystick_button_10_triggered[0x10];
extern unsigned int joystick_button_11_triggered[0x10];
extern unsigned int joystick_button_12_triggered[0x10];
extern unsigned int joystick_button_13_triggered[0x10];
extern unsigned int joystick_button_14_triggered[0x10];
extern unsigned int joystick_button_15_triggered[0x10];
extern unsigned int joystick_button_16_triggered[0x30];
extern void *force_feedback_effect_handles2[4];
extern unsigned char g_EffectBuffer1[0x190];
extern unsigned int g_EffectBuffer2[0x64];
extern unsigned int g_EffectScaleFactor;
extern unsigned char g_JoystickButtonState[1];
extern unsigned char g_JoystickDataFormat;
extern unsigned char g_JoystickStateBuffer[1];
extern unsigned int g_JoystickStateFlags[0x10];
extern unsigned char g_KeyboardDataFormat;
extern unsigned short g_KeyboardState[1];
extern unsigned char g_MouseDataFormat;
extern unsigned int g_MouseMaxX;
extern unsigned int g_MouseMaxY;
extern unsigned int g_MouseMinX;
extern unsigned int g_MouseMinY;
extern unsigned int g_MouseX;
extern unsigned int g_MouseY[1];
extern unsigned int g_PlayerDeviceMap1[1];
extern unsigned int g_bDevicesAcquired;
extern unsigned int g_pDirectInput;
extern unsigned int g_pEffectStructs[0x3];
extern unsigned int g_pEffectStructs2[0x4];
extern unsigned int g_pJoystickDevices[0x4];
extern unsigned int g_pKeyboardDevice;
extern unsigned int g_pMouseDevice;
extern unsigned int g_uiNumJoysticks;
extern unsigned int hDlgInput;
extern int joystick_axis_1_negative_triggered[4];
extern int joystick_axis_1_positive_triggered[4];
extern int joystick_axis_2_negative_triggered[4];
extern int joystick_axis_2_positive_triggered[4];
extern int joystick_axis_3_negative_triggered[4];
extern int joystick_axis_3_positive_triggered[4];
extern int joystick_axis_4_negative_triggered[4];
extern int joystick_axis_4_positive_triggered[4];
extern int joystick_axis_5_negative_triggered[4];
extern int joystick_axis_5_positive_triggered[4];
extern int joystick_axis_6_negative_triggered[4];
extern int joystick_axis_6_positive_triggered[4];
extern int joystick_axis_7_negative_triggered[4];
extern int joystick_axis_7_positive_triggered[4];
extern int joystick_button_1_triggered[4];
extern int joystick_button_2_triggered[4];
extern unsigned int point_device_enabled;
extern unsigned short pad_axis_1_value[1];
extern unsigned short pad_axis_2_value[1];
extern unsigned short pad_axis_3_value[1];
extern unsigned short pad_axis_4_value[1];
extern unsigned short pad_axis_5_value[1];
extern unsigned short pad_axis_6_value[1];
extern unsigned short pad_axis_7_value[1];

/* Function prototypes (previously generated in src/_gen) */
int diAcquireAllDevices();
int diAcquireMouseDevice();
unsigned int __cdecl diCreateEffectHelper(int a1, _DWORD *a2);
int diEnumDevicesCallback(int a1, _DWORD *a2, int a3);
int __stdcall diEnumEffectsCallback(_DWORD *a1, _DWORD *a2);
int diGetClampedMouseX();
int diGetClampedMouseY();
int __cdecl diGetJoystickButtonState1(int a1);
int __cdecl diGetJoystickButtonState2(int a1);
int __cdecl diGetJoystickButtonState3(int a1);
int __cdecl diGetJoystickButtonState4(int a1);
int diGetMouseState();
int diInitDirectInput();
_DWORD *__cdecl diInitEffectStruct(_DWORD *a1);
int __cdecl diSetConstantForceMagnitude(int a1, int a2);
int __cdecl diSetEffectMagnitude(int a1, int a2, int a3, int a4);
int __cdecl diSetPeriodicForceMagnitude(_DWORD *a1, int a2);
unsigned int __cdecl diSetupConstantForceEffect(int a1, int a2);
unsigned int __cdecl diSetupPeriodicForceEffect(_DWORD *a1, int a2);
int diShutdownDirectInput();
int diUnacquireAllDevices();
int diUpdateDeviceStates();
int diUpdateJoystickStates();
