#pragma once

typedef struct _KBD_NAME {
	char text[13];
} KBD_NAME;

typedef struct _JOY_NAME {
	char text[14];
} JOY_NAME;
/* Decompiled globals (previously generated in src/_gen) */
extern GUID GUID_Keyboard;
extern GUID GUID_Mouse;
extern unsigned char byte_4F777C;
extern unsigned char byte_4F77B8[1];
extern unsigned char byte_4F77B9[1];
extern unsigned char byte_4F77BA[1];
extern unsigned char byte_4F77BB[1];
extern unsigned char byte_4F77BC[1];
extern unsigned char byte_4F77BD[1];
extern unsigned char byte_4F77BE[1];
extern unsigned char byte_4F77BF[1];
extern unsigned char byte_4F77C0[1];
extern unsigned char byte_4F77C1[1];
extern unsigned char byte_4F77C2[1];
extern unsigned char byte_4F77C3[1];
extern unsigned char byte_4F77C4[1];
extern unsigned char byte_4F77C5[1];
extern unsigned char byte_4F77C6[1];
extern unsigned char byte_4F77C7[0x101];
extern unsigned char byte_50ACC0[1];
extern unsigned char byte_50ACC1[1];
extern unsigned char byte_50ACC2[1];
extern unsigned char byte_50ACC3[1];
extern unsigned char byte_50ACC4[1];
extern unsigned char byte_50ACC5[1];
extern unsigned char byte_50ACC6[1];
extern unsigned char byte_50ACC7[1];
extern unsigned char byte_50ACC8[1];
extern unsigned char byte_50ACC9[1];
extern unsigned char byte_50ACCA[1];
extern unsigned char byte_50ACCB[1];
extern unsigned char byte_50ACCC[1];
extern unsigned char byte_50ACCD[1];
extern unsigned char byte_50ACD0[1];
extern unsigned char byte_50ACD1[1];
extern unsigned char byte_50ACD2[1];
extern unsigned char byte_50ACD3[1];
extern unsigned char byte_50ACD4[1];
extern unsigned char byte_50ACD5[1];
extern unsigned char byte_50ACD6[1];
extern unsigned char byte_50ACD7[1];
extern unsigned char byte_50ACD8[1];
extern unsigned char byte_50ACD9[1];
extern unsigned char byte_50ACDA[1];
extern unsigned char byte_50ACDB[1];
extern unsigned char byte_50ACDC[1];
extern unsigned char byte_50ACDD[1];
extern unsigned char byte_50ACDE[1];
extern unsigned char byte_50ACDF[0x61];
extern unsigned char byte_50AD41[1];
extern unsigned char byte_50AD42[1];
extern unsigned char byte_50AD43[0x7d];
extern unsigned int dword_4F778C[1];
extern unsigned int dword_4F7790[1];
extern unsigned int dword_4F7798[1];
extern unsigned int dword_4F779C[1];
extern unsigned int dword_4F77A0[1];
extern unsigned int dword_4F77A4[1];
extern unsigned int dword_4F77A8[0x4];
extern unsigned int dword_4F7B68[0x10];
extern unsigned int dword_4F7EE8[0x10];
extern unsigned int dword_4F7F28[0x10];
extern unsigned int dword_4F7F68[0x10];
extern unsigned int dword_4F7FA8[0x10];
extern unsigned int dword_4F7FE8[0x10];
extern unsigned int dword_4F8028[0x10];
extern unsigned int dword_4F8068[0x10];
extern unsigned int dword_4F80A8[0x10];
extern unsigned int dword_4F80E8[0x10];
extern unsigned int dword_4F8128[0x10];
extern unsigned int dword_4F8168[0x10];
extern unsigned int dword_4F81A8[0x10];
extern unsigned int dword_4F81E8[0x10];
extern unsigned int dword_4F8228[0x30];
extern void *force_feedback_effect_handles2[4];
extern unsigned char g_EffectBuffer1[0x190];
extern unsigned int g_EffectBuffer2[0x64];
extern unsigned int g_EffectScaleFactor;
extern unsigned char g_JoystickButtonState[1];
extern unsigned char g_JoystickDataFormat;
extern unsigned char g_JoystickStateBuffer[1];
extern unsigned int g_JoystickStateFlags[0x10];
extern unsigned char g_KeyboardDataFormat;
extern unsigned short g_KeyboardState[1];
extern unsigned char g_MouseDataFormat;
extern unsigned int g_MouseMaxX;
extern unsigned int g_MouseMaxY;
extern unsigned int g_MouseMinX;
extern unsigned int g_MouseMinY;
extern unsigned int g_MouseX;
extern unsigned int g_MouseY[1];
extern unsigned int g_PlayerDeviceMap1[1];
extern unsigned int g_bDevicesAcquired;
extern unsigned int g_pDirectInput;
extern unsigned int g_pEffectStructs[0x3];
extern unsigned int g_pEffectStructs2[0x4];
extern unsigned int g_pJoystickDevices[0x4];
extern unsigned int g_pKeyboardDevice;
extern unsigned int g_pMouseDevice;
extern unsigned int g_uiNumJoysticks;
extern unsigned int hDlgInput;
extern int joystick_axis_1_negative_triggered[4];
extern int joystick_axis_1_positive_triggered[4];
extern int joystick_axis_2_negative_triggered[4];
extern int joystick_axis_2_positive_triggered[4];
extern int joystick_axis_3_negative_triggered[4];
extern int joystick_axis_3_positive_triggered[4];
extern int joystick_axis_4_negative_triggered[4];
extern int joystick_axis_4_positive_triggered[4];
extern int joystick_axis_5_negative_triggered[4];
extern int joystick_axis_5_positive_triggered[4];
extern int joystick_axis_6_negative_triggered[4];
extern int joystick_axis_6_positive_triggered[4];
extern int joystick_axis_7_negative_triggered[4];
extern int joystick_axis_7_positive_triggered[4];
extern int joystick_button_1_triggered[4];
extern int joystick_button_2_triggered[4];
extern unsigned int point_device_enabled;
extern unsigned short word_50AE02[1];
extern unsigned short word_50AE04[1];
extern unsigned short word_50AE06[1];
extern unsigned short word_50AE08[1];
extern unsigned short word_50AE0A[1];
extern unsigned short word_50AE0C[1];
extern unsigned short word_50AE0E[1];

/* Function prototypes (previously generated in src/_gen) */
int diAcquireAllDevices();
int diAcquireMouseDevice();
unsigned int __cdecl diCreateEffectHelper(int a1, _DWORD *a2);
int diEnumDevicesCallback(int a1, _DWORD *a2, int a3);
int __stdcall diEnumEffectsCallback(_DWORD *a1, _DWORD *a2);
int diGetClampedMouseX();
int diGetClampedMouseY();
int __cdecl diGetJoystickButtonState1(int a1);
int __cdecl diGetJoystickButtonState2(int a1);
int __cdecl diGetJoystickButtonState3(int a1);
int __cdecl diGetJoystickButtonState4(int a1);
int diGetMouseState();
int diInitDirectInput();
_DWORD *__cdecl diInitEffectStruct(_DWORD *a1);
int __cdecl diSetConstantForceMagnitude(int a1, int a2);
int __cdecl diSetEffectMagnitude(int a1, int a2, int a3, int a4);
int __cdecl diSetPeriodicForceMagnitude(_DWORD *a1, int a2);
unsigned int __cdecl diSetupConstantForceEffect(int a1, int a2);
unsigned int __cdecl diSetupPeriodicForceEffect(_DWORD *a1, int a2);
int diShutdownDirectInput();
int diUnacquireAllDevices();
int diUpdateDeviceStates();
int diUpdateJoystickStates();
