#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern unsigned char byte_50C3E0[0x5a00];
extern unsigned int dword_4FD858;
extern unsigned short mdec_bit15_flag;
extern unsigned char mdec_color_lookup[0x80];
extern unsigned int mdec_color_table_0[0x80];
extern unsigned int mdec_color_table_1[0x80];
extern unsigned int mdec_color_table_2[0x80];
extern unsigned int mdec_color_table_3[0x80];
extern unsigned int mdec_color_table_4[0x80];
extern unsigned int mdec_color_table_5[0x80];
extern unsigned int mdec_color_table_6[0x80];
extern unsigned int mdec_color_table_7[0x80];
extern unsigned int mdec_command;
extern unsigned int mdec_dma_dest;
extern unsigned int mdec_idct_buffer[0xb40];
extern unsigned char mdec_idct_buffer_end[0x1680];
extern unsigned int mdec_image_size;
extern unsigned int mdec_in_ptr;
extern unsigned char mdec_mono_table_0[0x100];
extern unsigned char mdec_mono_table_1[0x80];
extern unsigned char mdec_mono_table_2[0x100];
extern unsigned int mdec_nonzero_counts[0xb8];
extern unsigned int mdec_out_addr;
extern unsigned int mdec_param_word;
extern unsigned int mdec_scale_table[0x20];
extern unsigned int mdec_status;
extern unsigned char mdec_timer;
extern unsigned int mdec_timer_count;
extern unsigned int mdec_zigzag[13];
extern unsigned __int64 qword_455C20;
extern unsigned __int64 qword_455C28;
extern unsigned __int64 qword_455C30;
extern unsigned __int64 qword_455C38;
extern unsigned __int64 qword_455C40;
extern unsigned __int64 qword_455C50;
extern unsigned __int64 qword_455C58;
extern unsigned __int64 qword_455C60;
extern unsigned __int64 qword_455C68;
extern unsigned __int64 qword_455C70;
extern unsigned __int64 qword_455C78;

/* Function prototypes (previously generated in src/_gen) */
int mdec_decode();
void mdec_dma_in_handler();
int __cdecl mdec_freeze(const char *a1, int a2);
int __cdecl mdec_freeze2(const char *a1, int a2);
int __cdecl mdec_handle_special_command(int a1);
void __cdecl mdec_idct_blocks(int a1);
int __cdecl mdec_idct_sse(__m64 *a1, int a2);
int mdec_init();
int mdec_init_color_tables();
char *mdec_init_pointers();
char *__cdecl mdec_rl_decode(char *a1, int a2);
int __cdecl mdec_set_scale_table(int a1);
void mdec_sse_m_empty();
char mdec_timer_handler();
int __cdecl mdec_unfreeze(int a1, _DWORD *a2);
int __cdecl mdec_unfreeze2(int a1, _DWORD *a2);
__int16 __cdecl mdec_write_command(unsigned int a1);
void __cdecl mdec_y_to_mono(unsigned int *a1, __m64 *a2, int a3);
_WORD *__cdecl mdec_yuv_to_rgb(char *a1, _WORD *a2, _WORD *a3);
