#pragma once

void op_SLL();
void op_SRL();
void op_SRA();
void op_SLLV();
void op_SRLV();
void op_SRAV();
void op_JR();
void op_JALR();
void op_SYSCALL();
void op_BREAK();
void op_MFHI();
void op_MTHI();
void op_MFLO();
void op_MTLO();
void op_MULT();
void op_MULTU();
void op_DIV();
void op_DIVU();
void op_ADD();
void op_SUB();
void op_AND();
void op_OR();
void op_XOR();
void op_NOR();
void op_SLT();
void op_SLTU();
void op_MFC0();
void op_MTC0();
void op_RFE();
void op_BLTZ();
void op_BGEZ();
void op_BLTZAL();
void op_BGEZAL();
void op_J();
void op_JAL();
void op_BEQ();
void op_BNE();
void op_BLEZ();
void op_BGTZ();
void op_ADDI();
void op_SLTI();
void op_SLTIU();
void op_ANDI();
void op_ORI();
void op_XORI();
void op_LUI();
void op_LB();
void op_LH();
void op_LWL();
void op_LW();
void op_LBU();
void op_LHU();
void op_LWR();
void op_SB();
void op_SH();
void op_SWL();
void op_SW();
void op_SWR();
void op_LWC2();
void op_SWC2();
void op_UNKNOWN();

/* Decompiled globals (previously generated in src/_gen) */
extern unsigned char xenogears_cd_detected;
extern unsigned int cop0_regs[1];
extern unsigned int cop0_sr;
extern unsigned int cop0_cause;
extern unsigned int cop0_epc;
