#pragma once
/* Decompiled globals (previously generated in src/_gen) */
extern unsigned char Memcard1[0x400];
extern unsigned char Memcard2[0x400];
extern unsigned char controller_config_response_byte;
extern unsigned char netplay_memcard_buffer[0x3820];
extern unsigned char controller2_id_byte;
extern unsigned char controller2_response_constant;
extern unsigned char sio_freeze_state[0x4];
extern unsigned char memcard1_directory_next_block[1];
extern unsigned char memcard1_directory_frame[0x76];
extern unsigned char memcard1_directory_checksum[0x701];
extern unsigned char memcard1_block_state_byte0[1];
extern unsigned char memcard1_block_state_byte1[1];
extern unsigned char memcard1_block_state_byte2[1];
extern unsigned char memcard1_block_state_byte3[1];
extern unsigned char memcard1_block_next_block[1];
extern unsigned char memcard1_save_data[0x1f7f7];
extern unsigned char memcard2_header[0x7e];
extern unsigned char memcard2_header_checksum;
extern unsigned char memcard2_directory_state[1];
extern unsigned char memcard2_directory_next_block[1];
extern unsigned char memcard2_directory_frame[0x76];
extern unsigned char memcard2_directory_checksum[0x701];
extern unsigned char memcard2_buffer[0x1f902];
extern unsigned int memcard2_checksum;
extern unsigned char memcard2_data[0x2000];
extern unsigned char memcard2_id_byte;
extern unsigned int memcard_current_address;
extern unsigned char pad_analog_mode_flags[8];
extern unsigned char rumble_big_motor_state[8];
extern unsigned char rumble_small_motor_state[8];
extern unsigned int sio0_mode_reg;
extern unsigned char sio_config_data[19];
extern unsigned char sio_controller_response_alt[1];
extern unsigned char sio_controller_response_buffer[1];
extern unsigned char sio_controller_slot_index;
extern unsigned char sio_controller_state[0x4];
extern unsigned char sio_last_command_slot[1];
extern unsigned int sio_memcard1_dirty_counter;
extern unsigned int sio_memcard1_file_offset;
extern unsigned int sio_memcard2_dirty_counter;
extern unsigned int sio_memcard2_file_offset;
extern unsigned char sio_memcard_data_slot1[1];
extern unsigned char sio_memcard_data_slot2[1];
extern unsigned char sio_memcard_loaded;
extern unsigned char sio_multitap_command_buffer[0x40];
extern unsigned char sio_multitap_command_byte[0x40];
extern unsigned int sio_multitap_slot_counter;
extern unsigned int sio_multitap_state;
extern unsigned char sio_response_buffer_analog_byte[8];
extern unsigned char sio_response_buffer_config_byte[8];
extern unsigned char sio_response_buffer_config_byte2[8];
extern unsigned char sio_response_buffer_config_byte3[8];
extern unsigned char sio_response_buffer_data1[0x100];
extern unsigned char sio_response_buffer_data2[0x100];
extern unsigned char sio_response_buffer_id[8];
extern unsigned int sio_rx_fifo_count;
extern unsigned int sio_transfer_length;
extern unsigned int sio_transfer_pending;
extern unsigned int sio_transfer_timeout;
extern unsigned char sio_tx_fifo[0x104];
extern unsigned char sio_tx_fifo_data[0x100];

/* Function prototypes (previously generated in src/_gen) */
int save_temp_memcard1();
int save_temp_memcard2();
bool sio_controller_init(int16_t a1);
char * sio_for_netplay(uint8_t a1);
int sio_freeze(const char *a1, int a2);
char sio_memcard_auto_save();
char sio_memcard_both_save();
char sio_memcard_load();
void sio_read_data_byte();
int sio_read_register(int a1, char a2);
int (__stdcall *sio_reset_all())(uint32_t);
void sio_trigger_rx_ready_irq();
void sio_unfreeze(int a1, uint32_t *a2);
void sio_write_data_byte(int a1, char a2);
